### ISSUE TITLE
Support CKOZ-00/13

### ISSUE THREAD

**Issue by gbbirkisson** [karloygard/xcomfortd#8]
Hi,
I am trying to use the CKOZ-00/13 usb stick with this code. 

I naively tried to just change the [device id](https://github.com/karloygard/xcomfortd/blob/443f95cf1f0acdf5bf7ff2cee659f619d24b3c0c/usb.cpp#L205) in the code to:

```
handle = libusb_open_device_with_vid_pid(context, 0x188a, 0x1102);
```

And that resulted in a LIBUSB_ERROR_IO when doing [libusb_submit_transfer(recv_transfer);](https://github.com/karloygard/xcomfortd/blob/443f95cf1f0acdf5bf7ff2cee659f619d24b3c0c/usb.cpp#L256).

Do you have an idea of how hard it would be to support CKOZ-00/13?

**Comment by karloygard** [comment]
The main code can't support the 00/13 device, they are too different. However, there is some code in the ckoz0013 folder, from an abandoned attempt at supporting that device. You can play around with that, if you like.

In the end I gave up and got the 00/14 device as well, it's specifically made to be used in home automation. The 00/13 device is intended to only be used for configuring the network. If you want to add/remove devices or just change the configuration, you really will need both. It's an annoying fact of the xComfort system, but until Eaton changes something, it's unfortunately the way it is.

**Comment by gbbirkisson** [comment]
Thank you for the answer. I will probably just get the 00/14. Awesome project :+1:

**Comment by karloygard** [comment]
If you have more modern xComfort devices that use the extended status reporting, this code is of limited use for you. I have a newer repo which supports that and is written in go instead, but I haven't released it yet. Let me know if you want to take a look when you get the 00/14.

Ideally, this code would be integrated with Home Assistant, but as far as I could tell, that requires writing it in python, which I haven't yet bothered learning.

**Comment by hans99** [comment]
I would really like to have a "go", please :) Can you publish it here?

**Comment by karloygard** [comment]
Let me fix it up a bit, and I'll publish it tomorrow-ish.

**Comment by gbbirkisson** [comment]
Yeah I'm also very interested in that piece of code. As for the home assistant integration, I was just planning to create a add-on for the time being. But I am familiar with both go and python so I could potentially port it.

**Comment by hans99** [comment]
Dette syns veldi spännande :)

**Comment by gbbirkisson** [comment]
After thinking about this, it think we basically have 2 options:

#### 1. Use the Home Assistant MQTT auto discovery

This is quite easy to do. It just means that you have to send 1 extra message to the HA discovery topic when xComfortd starts to send to HA what devices are available. I have experience with doing that and it works pretty well.

#### 2. Create a Home Assistant integration

This would be more involved. But we could basically model it after the deConz integration. It would mean that xComfortd has to run an API that HA can communicate with. Then the integration would use that API to setup and control the devices. That way xComfortd can just be written in go, and we do not have to port it.

#### Going forward

I really want to make this happen. I would be more than happy to implement either of those options (in the golang version of xComfortd). Personally I think that option 2 would be nicer for HA but I think we should start with option 1.

I can also create the home assistant addon images to support multiple architectures and create the addon for home assistant.

**Comment by karloygard** [comment]
This is very encouraging. Either of those options would be a huge improvement over having to fiddle with manual configuration.

I didn't find time to clean up the code during the week, but I'll work at little on it tomorrow, which hopefully should be sufficient to weed out the most embarrassing issues.
