### ISSUE TITLE
Not finding my usb on HassOS 3.12

### ISSUE THREAD

**Issue by geeewizzz** [karloygard/xcomfortd#9]
Hi,

I'm a total noob in both hassio and its addons.

I was very enthusiastic when I found this project, really looking forward to getting it to work. Yesterday I got my CKOZ 00/14 stick. Included it in the Eaton MRF and got it included in my setup. I went on to plug it into my rpi that is running HassOS 3.12, the USB lights up green and I see the little red light flickering when I turn on or off my devices.

The problem I'm facing is that I cant get the xcomfortd executable to run, most likely because it can't find my USB stick. I can't see it in the list of hardware:

<img width="406" alt="Screenshot 2020-04-09 at 12 03 57" src="https://user-images.githubusercontent.com/4536023/78883772-3dc22380-7a5a-11ea-8728-6f290864dbf6.png">

The pi is definitely seeing the usb though, I'm just not able to communicate with it(?):
<img width="1149" alt="Screenshot 2020-04-09 at 12 16 19" src="https://user-images.githubusercontent.com/4536023/78884922-005e9580-7a5c-11ea-887b-43c98fd4d81b.png">

After creating the executable, adding the packages needed and running xcomfortd I'm getting this:
<img width="399" alt="Screenshot 2020-04-09 at 12 25 27" src="https://user-images.githubusercontent.com/4536023/78885632-3bad9400-7a5d-11ea-9b5d-28299b147972.png">

Please help me. What am I doing wrong?

**Comment by geeewizzz** [comment]
I made some progress so this can be closed, decided to reinstall hassio on raspbian instead. 
<img width="479" alt="Screenshot 2020-04-09 at 22 52 47" src="https://user-images.githubusercontent.com/4536023/78939736-fae16980-7ab4-11ea-8225-2007474f51f5.png">

**Comment by karloygard** [comment]
You are in luck, I'm working on a newer version of this code, which should be more stable and be more flexible. Another user is working on a hassio addon, which should make this much more user friendly as well. I can ping you when it's released to the public (mere days away now).

**Comment by geeewizzz** [comment]
That is amazing news, yes please let me know. Looking forward to it!

**Comment by geeewizzz** [comment]
@karloygard Any chance you will support heating sensors and/or the room controller touch in the new version? So that it will be possible turn on/off floor heating based on a temp read a sensor either in the room controller touch or a floor sensor?

**Comment by geeewizzz** [comment]
And by the way, actually got it working after some fiddling around. So it's not that user unfriendly!
<img width="572" alt="Screenshot 2020-04-10 at 00 16 29" src="https://user-images.githubusercontent.com/4536023/78945453-9c21ed00-7ac0-11ea-98bc-19bc0cc940da.png">

**Comment by karloygard** [comment]
> @karloygard Any chance you will support heating sensors and/or the room controller touch in the new version? So that it will be possible turn on/off floor heating based on a temp read a sensor either in the room controller touch or a floor sensor?

Might be possible with some assistance from you. Which devices do you have, and how have you configured them?

**Comment by geeewizzz** [comment]
@karloygard 
I have a few room controller touch devices, they have in built sensors in the devices, mine have attached an external sensor called pt1000 that monitors the temp of the actual floor (not the room). 
These devices control heating actuators that turn on/off the floor heating in my bathrooms and hallways.

In addition to this i have something that came out before the room controller touch called temperature sensor, which is a device that is similar to the stand alone pt1000(i guess). It monitors and reports the temp in the floor so that it can send signals to the heating actuators to turn on/off.

My system is programmed using the ckoz 00/13, using the Eaton MRF software.

You can find my email adr in my profile page if you would like more details or want me to test something, I will happily contribute with whatever I can.

**Comment by karloygard** [comment]
Check out https://github.com/karloygard/hassio-addons. Open up Home Assistant, go to Supervisor -> Add-On Store and add a new repository with that url.

If you send me the datapoints file mentioned in the documentation for the addon, I can try to make sure that your devices will work with this code.

**Comment by geeewizzz** [comment]
Hi,

I have added a few of my varmekabler(!) and stuff here and exported the datapoints file from the usb stick.

Will try to get the add-on working today. Cool, thanks!

Geir
On 11 Apr 2020, 11:39 +0200, Karl Anders Øygard <notifications@github.com>, wrote:
> Check out https://github.com/karloygard/hassio-addons. Open up Home Assistant, go to Supervisor -> Add-On Store and add a new repository with that url.
> If you send me the datapoints file mentioned in the documentation for the addon, I can try to make sure that your devices will work with this code.
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.

1	bakdør utelys  	5709360	16	0	0	0	#000#000#000#000#0#000#000#005#000#	
2	1.etg sov 4 	5740117	17	0	0	0	#000#000#000#000#0#000#000#006#000#	
3	1.etg sov 3 	5734031	17	0	0	0	#000#000#000#000#0#000#000#006#000#	
4	1.etg sov 2 	5740097	17	0	0	0	#000#000#000#000#0#000#000#006#000#	
5	1.etg sov.1 	5733990	17	0	0	0	#000#000#000#000#0#000#000#006#000#	
6	1.etg bad speil 	5736891	17	0	0	0	#000#000#000#000#0#000#000#006#000#	
7	1.etg bad tak 	5736925	17	0	0	0	#000#000#000#000#0#000#000#006#000#	
8	1.etg stor gang 	5734000	17	0	0	0	#000#000#000#000#0#000#000#006#000#	
9	utelys hoveddør 	5727252	16	0	0	0	#000#000#000#000#0#000#000#005#000#	
10	1.etg tv stue 	5733992	17	0	0	0	#000#000#000#000#0#000#000#006#000#	
11	1.etg liten gang 	5734068	17	0	0	0	#000#000#000#000#0#000#000#006#000#	
12	1.etg kjøkken spotter 	5734274	17	0	0	0	#000#000#000#000#0#000#000#006#000#	
13	1.etg stue lampe spi  	5741956	17	0	0	0	#000#000#000#000#0#000#000#006#000#	
14	utelys terrasse 	5733605	16	0	0	0	#000#000#000#000#0#000#000#005#000#	
16	1.etg bad vk 	5727387	16	0	0	0	#000#000#000#000#0#000#000#005#000#	
20	1.etg dusj/bad vk 	5727267	16	0	0	0	#000#000#000#000#0#000#000#005#000#	
22	1.etg liten gang vk 	5733608	16	0	0	0	#000#000#000#000#0#000#000#005#000#	
24	1.etg stor gang vk 	5733583	16	0	0	0	#000#000#000#000#0#000#000#005#000#	
15	1.etg bad temp   (Kanal B)	5881271	23	1	1	1	#000#000#000#000#0#000#000#006#000#	
17	1.etg dusj/bad  (ekstern Sensor (PT1000))	6784078	78	6	1	1	#000#000#000#000#0#000#000#001#000#	
18	1.etg dusj/bad  (Touch-sensor A)	6784078	78	4	1	1	#000#000#000#000#0#000#000#001#000#	
19	1.etg dusj/bad  (Touch-sensor B)	6784078	78	5	1	1	#000#000#000#000#0#000#000#001#000#	
21	1.etg liten gang temp  (Kanal A)	5881353	23	0	1	1	#000#000#000#000#0#000#000#006#000#	
23	1.etg stor gang temp   (Kanal B)	5881341	23	1	1	1	#000#000#000#000#0#000#000#006#000#

**Comment by geeewizzz** [comment]
Just replied to the email, guess we should move this discussion to the right place.
